name: features
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5

#  for internet status
  connectivity_plus: ^3.0.3

#  for toast
  fluttertoast: ^8.2.1

#  for device info
  device_info_plus: ^8.1.0

#  to find current location of device
  geolocator: ^9.0.2

#  to get location name
  geocoding: ^2.1.0

#  for notification badge
  awesome_notifications: ^0.7.4+1
  http: ^0.13.5
  lottie: ^2.3.1
  shared_preferences: ^2.0.20
  intl: ^0.17.0
  cloud_firestore: ^4.4.5
  firebase_core: ^2.8.0
  data_table_2: ^2.4.1
  pdf: ^3.10.1
  path_provider: ^2.0.14
  url_launcher: ^6.1.10

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:

  uses-material-design: true
  assets:
    - assets/ic_launcher.png
    - assets/90751-android-app-background.json
    - assets/Caveat-Regular.ttf
    - assets/606284.jpg

  fonts:
    - family: Caveat
      fonts:
        - asset: assets/Caveat-Regular.ttf
          style: normal
    
