// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0n0AurYf2EsxE5fgey6LkWaxgOPS8dAc',
    appId: '1:407507047827:web:58a4ec61600fd1b8fc8466',
    messagingSenderId: '407507047827',
    projectId: 'features-f3fad',
    authDomain: 'features-f3fad.firebaseapp.com',
    storageBucket: 'features-f3fad.appspot.com',
    measurementId: 'G-QEHCH9DL8B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgY0cYkTol64HpJcEQCNene_UjBxMVCeo',
    appId: '1:407507047827:android:7f84d2da6d577f03fc8466',
    messagingSenderId: '407507047827',
    projectId: 'features-f3fad',
    storageBucket: 'features-f3fad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9yT5QcnxFAGItwaOaULWFwFi1VIHGpjc',
    appId: '1:407507047827:ios:fc11324e0a49b161fc8466',
    messagingSenderId: '407507047827',
    projectId: 'features-f3fad',
    storageBucket: 'features-f3fad.appspot.com',
    iosClientId: '407507047827-4h2hvi3sj0f4vuo2n734r87djgojaqkh.apps.googleusercontent.com',
    iosBundleId: 'com.example.features',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9yT5QcnxFAGItwaOaULWFwFi1VIHGpjc',
    appId: '1:407507047827:ios:fc11324e0a49b161fc8466',
    messagingSenderId: '407507047827',
    projectId: 'features-f3fad',
    storageBucket: 'features-f3fad.appspot.com',
    iosClientId: '407507047827-4h2hvi3sj0f4vuo2n734r87djgojaqkh.apps.googleusercontent.com',
    iosBundleId: 'com.example.features',
  );
}
